-- Description: online documents module ("docs") — spaces, pages, collaboration
-- state, permissions, comments, attachments, sharing, notifications, templates,
-- labels, import jobs — plus tenant-level user groups.
--
-- Design: docs/在线文档技术方案 §2 (data model) and §3 (permissions).
--
-- Conventions, matching the rest of the schema:
--   * VARCHAR(36) UUID primary keys generated by the application;
--   * tenant_id BIGINT on every table so each query can be pinned to a tenant
--     without joins; no FK to tenants (the rest of the schema does not FK it);
--   * soft deletes via deleted_at; hard deletion happens from the trash purge
--     and relies on ON DELETE CASCADE between docs_* tables;
--   * JSONB for ProseMirror content and small structured columns, BYTEA for the
--     Yjs collaboration state (the collaboration truth source; the JSON column
--     is its projection).
--
-- Numbering: the docs module owns 000120–000139 so it can land independently
-- of migrations produced by other work streams.

DO $$ BEGIN RAISE NOTICE '[Migration 000120] Creating docs module tables...'; END $$;

-- pg_trgm powers fuzzy title search. It is optional: on a managed database
-- where the extension cannot be created, the trigram index is simply skipped
-- and title search falls back to ILIKE (the repository detects the index).
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE '[Migration 000120] pg_trgm not available (%), fuzzy title search will use ILIKE', SQLERRM;
END $$;

-- ---------------------------------------------------------------------------
-- Tenant-level user groups (a general Yuheng capability, first consumed here)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tenant_groups (
    id           VARCHAR(36)  PRIMARY KEY,
    tenant_id    BIGINT       NOT NULL,
    name         VARCHAR(128) NOT NULL,
    description  TEXT         NOT NULL DEFAULT '',
    -- The default group implicitly contains every active tenant member; it is
    -- how "everyone in the workspace" is granted without enumerating users.
    is_default   BOOLEAN      NOT NULL DEFAULT FALSE,
    -- manual | oidc | ldap: where membership is managed.
    source       VARCHAR(16)  NOT NULL DEFAULT 'manual',
    external_id  VARCHAR(255),
    creator_id   VARCHAR(36),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_tenant_groups_name
    ON tenant_groups (tenant_id, name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_tenant_groups_default
    ON tenant_groups (tenant_id) WHERE is_default = TRUE AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS tenant_group_members (
    group_id   VARCHAR(36) NOT NULL REFERENCES tenant_groups(id) ON DELETE CASCADE,
    user_id    VARCHAR(36) NOT NULL,
    tenant_id  BIGINT      NOT NULL,
    added_by   VARCHAR(36),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (group_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_tenant_group_members_user
    ON tenant_group_members (tenant_id, user_id);

-- ---------------------------------------------------------------------------
-- Spaces and membership
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_spaces (
    id                  VARCHAR(36)  PRIMARY KEY,
    tenant_id           BIGINT       NOT NULL,
    slug                VARCHAR(64)  NOT NULL,
    name                VARCHAR(255) NOT NULL,
    description         TEXT         NOT NULL DEFAULT '',
    icon                VARCHAR(64),
    -- private: explicit members only; open: every tenant member gets
    -- default_role; public: readable without login (see docs_shares for the
    -- per-page variant).
    visibility          VARCHAR(16)  NOT NULL DEFAULT 'private'
                        CHECK (visibility IN ('private', 'open', 'public')),
    default_role        VARCHAR(16)  NOT NULL DEFAULT 'none'
                        CHECK (default_role IN ('none', 'reader', 'writer')),
    knowledge_base_id   VARCHAR(36),
    storage_backend_id  VARCHAR(36),
    settings            JSONB        NOT NULL DEFAULT '{}'::JSONB,
    -- Attachment bytes this space may hold; 0 means unlimited, as everywhere
    -- else in Yuheng. A column rather than a key in settings: settings is
    -- writable by a space administrator, and a quota somebody can raise for
    -- themselves is not a quota. Only a workspace administrator may set it.
    quota_bytes         BIGINT       NOT NULL DEFAULT 0 CHECK (quota_bytes >= 0),
    creator_id          VARCHAR(36),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_docs_spaces_slug
    ON docs_spaces (tenant_id, slug) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_docs_spaces_tenant
    ON docs_spaces (tenant_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_docs_spaces_kb
    ON docs_spaces (knowledge_base_id) WHERE knowledge_base_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS docs_space_members (
    id              VARCHAR(36) PRIMARY KEY,
    space_id        VARCHAR(36) NOT NULL REFERENCES docs_spaces(id) ON DELETE CASCADE,
    tenant_id       BIGINT      NOT NULL,
    principal_type  VARCHAR(8)  NOT NULL CHECK (principal_type IN ('user', 'group')),
    principal_id    VARCHAR(36) NOT NULL,
    role            VARCHAR(16) NOT NULL CHECK (role IN ('admin', 'writer', 'reader')),
    added_by        VARCHAR(36),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (space_id, principal_type, principal_id)
);
CREATE INDEX IF NOT EXISTS idx_docs_space_members_principal
    ON docs_space_members (tenant_id, principal_type, principal_id);

-- ---------------------------------------------------------------------------
-- Pages
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_pages (
    id                  VARCHAR(36)  PRIMARY KEY,
    -- URL identity, stable across renames: /docs/{space}/{title-slug}-{short_id}
    short_id            VARCHAR(12)  NOT NULL,
    tenant_id           BIGINT       NOT NULL,
    space_id            VARCHAR(36)  NOT NULL REFERENCES docs_spaces(id) ON DELETE CASCADE,
    parent_id           VARCHAR(36)  REFERENCES docs_pages(id) ON DELETE CASCADE,
    -- Fractional index (Base62 string). Moving a page rewrites one row.
    position            VARCHAR(64)  COLLATE "C" NOT NULL DEFAULT '',
    title               VARCHAR(512) NOT NULL DEFAULT '',
    icon                VARCHAR(64),
    cover               VARCHAR(1024),
    -- ProseMirror JSON: projection of ydoc, produced by the collaboration
    -- service on persist. Input to rendering, search and history.
    content             JSONB,
    -- Yjs full state (encodeStateAsUpdate). Collaboration truth source; only
    -- the collaboration service reads or writes it.
    ydoc                BYTEA,
    -- Bumped on every persist; the persist path uses it for optimistic
    -- concurrency (UPDATE ... WHERE ydoc_version = base).
    ydoc_version        BIGINT       NOT NULL DEFAULT 0,
    text_content        TEXT         NOT NULL DEFAULT '',
    tsv                 tsvector GENERATED ALWAYS AS (
                            setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
                            setweight(to_tsvector('simple', left(coalesce(text_content, ''), 1000000)), 'B')
                        ) STORED,
    status              VARCHAR(16)  NOT NULL DEFAULT 'published'
                        CHECK (status IN ('draft', 'published')),
    is_locked           BOOLEAN      NOT NULL DEFAULT FALSE,
    template_id         VARCHAR(36),
    -- Knowledge entry IDs this page was distilled from (AI write-back).
    source_refs         JSONB        NOT NULL DEFAULT '[]'::JSONB,
    -- The knowledge entry this page is mirrored into, when its space is
    -- bound to a knowledge base and the page is eligible for indexing (see
    -- internal/docs/index). NULL means "not indexed", which is the state of
    -- every restricted page, draft and trashed page by design.
    knowledge_id        VARCHAR(36),
    -- Distinct editor user IDs, maintained by the persist path.
    contributor_ids     JSONB        NOT NULL DEFAULT '[]'::JSONB,
    creator_id          VARCHAR(36),
    last_editor_id      VARCHAR(36),
    deleted_by          VARCHAR(36),
    word_count          INTEGER      NOT NULL DEFAULT 0,
    attachment_bytes    BIGINT       NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    -- Only advances when the body changes (not on rename/move).
    content_updated_at  TIMESTAMPTZ,
    deleted_at          TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_docs_pages_short_id
    ON docs_pages (tenant_id, short_id);
-- Sibling listing: children of one parent in reading order.
CREATE INDEX IF NOT EXISTS idx_docs_pages_tree
    ON docs_pages (space_id, parent_id, position) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_docs_pages_space_updated
    ON docs_pages (tenant_id, space_id, updated_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_docs_pages_trash
    ON docs_pages (space_id, deleted_at) WHERE deleted_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_docs_pages_tsv
    ON docs_pages USING GIN (tsv);
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm') THEN
        CREATE INDEX IF NOT EXISTS idx_docs_pages_title_trgm
            ON docs_pages USING GIN (title gin_trgm_ops);
    END IF;
END $$;

-- Content snapshots for history, diff and restore (never the ydoc).
CREATE TABLE IF NOT EXISTS docs_page_revisions (
    id            VARCHAR(36)  PRIMARY KEY,
    page_id       VARCHAR(36)  NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,
    tenant_id     BIGINT       NOT NULL,
    space_id      VARCHAR(36)  NOT NULL,
    version       INTEGER      NOT NULL,
    title         VARCHAR(512) NOT NULL DEFAULT '',
    icon          VARCHAR(64),
    content       JSONB        NOT NULL,
    text_content  TEXT         NOT NULL DEFAULT '',
    editor_ids    JSONB        NOT NULL DEFAULT '[]'::JSONB,
    -- interval | publish | restore | import | manual
    reason        VARCHAR(16)  NOT NULL DEFAULT 'interval',
    created_by    VARCHAR(36),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE (page_id, version)
);
CREATE INDEX IF NOT EXISTS idx_docs_page_revisions_page
    ON docs_page_revisions (page_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Page-level permissions: a row exists only for pages that cut inheritance.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_page_access (
    page_id     VARCHAR(36) PRIMARY KEY REFERENCES docs_pages(id) ON DELETE CASCADE,
    tenant_id   BIGINT      NOT NULL,
    space_id    VARCHAR(36) NOT NULL,
    mode        VARCHAR(16) NOT NULL DEFAULT 'restricted' CHECK (mode IN ('restricted')),
    created_by  VARCHAR(36),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_docs_page_access_space ON docs_page_access (space_id);

CREATE TABLE IF NOT EXISTS docs_page_grants (
    id              VARCHAR(36) PRIMARY KEY,
    page_id         VARCHAR(36) NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,
    tenant_id       BIGINT      NOT NULL,
    principal_type  VARCHAR(8)  NOT NULL CHECK (principal_type IN ('user', 'group')),
    principal_id    VARCHAR(36) NOT NULL,
    role            VARCHAR(16) NOT NULL CHECK (role IN ('admin', 'writer', 'reader')),
    added_by        VARCHAR(36),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (page_id, principal_type, principal_id)
);
CREATE INDEX IF NOT EXISTS idx_docs_page_grants_principal
    ON docs_page_grants (tenant_id, principal_type, principal_id);

-- ---------------------------------------------------------------------------
-- Comments
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_comments (
    id           VARCHAR(36) PRIMARY KEY,
    tenant_id    BIGINT      NOT NULL,
    space_id     VARCHAR(36) NOT NULL,
    page_id      VARCHAR(36) NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,
    parent_id    VARCHAR(36) REFERENCES docs_comments(id) ON DELETE CASCADE,
    -- ProseMirror JSON (paragraph root; see schema.ValidateOptions.AllowedRoot)
    body         JSONB       NOT NULL,
    -- The body as plain text, maintained by the service beside the JSON.
    -- Search matches on this: matching the JSON would hit structure keywords
    -- ("paragraph", "text") and would miss nothing a reader would call a hit.
    text_content TEXT        NOT NULL DEFAULT '',
    -- Yjs relative positions {from, to} of the commented range; NULL for a
    -- page-level comment or once the range no longer resolves.
    anchor       JSONB,
    quoted_text  TEXT,
    creator_id   VARCHAR(36) NOT NULL,
    resolved_at  TIMESTAMPTZ,
    resolved_by  VARCHAR(36),
    edited_at    TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_docs_comments_page
    ON docs_comments (page_id, created_at) WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Attachments (metadata; bytes live in the space's storage backend)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_attachments (
    id           VARCHAR(36)   PRIMARY KEY,
    tenant_id    BIGINT        NOT NULL,
    space_id     VARCHAR(36)   NOT NULL REFERENCES docs_spaces(id) ON DELETE CASCADE,
    page_id      VARCHAR(36)   REFERENCES docs_pages(id) ON DELETE SET NULL,
    -- provider://bucket/key as returned by FileService
    file_path    VARCHAR(1024) NOT NULL,
    file_name    VARCHAR(512)  NOT NULL,
    file_ext     VARCHAR(32)   NOT NULL DEFAULT '',
    mime         VARCHAR(255)  NOT NULL DEFAULT 'application/octet-stream',
    size_bytes   BIGINT        NOT NULL DEFAULT 0,
    sha256       CHAR(64),
    width        INTEGER,
    height       INTEGER,
    -- file | image | video | audio | diagram
    kind         VARCHAR(16)   NOT NULL DEFAULT 'file',
    uploader_id  VARCHAR(36),
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_docs_attachments_page ON docs_attachments (page_id);
CREATE INDEX IF NOT EXISTS idx_docs_attachments_space
    ON docs_attachments (space_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_docs_attachments_sha
    ON docs_attachments (tenant_id, sha256) WHERE sha256 IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Public sharing
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_shares (
    id                  VARCHAR(36)  PRIMARY KEY,
    tenant_id           BIGINT       NOT NULL,
    space_id            VARCHAR(36)  NOT NULL,
    page_id             VARCHAR(36)  NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,
    -- 32 random bytes, Base62; the whole authority of the link
    key                 VARCHAR(64)  NOT NULL UNIQUE,
    include_children    BOOLEAN      NOT NULL DEFAULT FALSE,
    allow_search_index  BOOLEAN      NOT NULL DEFAULT FALSE,
    password_hash       VARCHAR(255),
    expires_at          TIMESTAMPTZ,
    view_count          BIGINT       NOT NULL DEFAULT 0,
    creator_id          VARCHAR(36),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    revoked_at          TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_docs_shares_page ON docs_shares (page_id) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- Watching and notifications
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_watchers (
    id          VARCHAR(36) PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL,
    user_id     VARCHAR(36) NOT NULL,
    space_id    VARCHAR(36) NOT NULL REFERENCES docs_spaces(id) ON DELETE CASCADE,
    -- NULL = watching the whole space
    page_id     VARCHAR(36) REFERENCES docs_pages(id) ON DELETE CASCADE,
    -- manual | author | comment | mention
    reason      VARCHAR(16) NOT NULL DEFAULT 'manual',
    muted_at    TIMESTAMPTZ,
    created_by  VARCHAR(36),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_docs_watchers_page
    ON docs_watchers (user_id, page_id) WHERE page_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_docs_watchers_space
    ON docs_watchers (user_id, space_id) WHERE page_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_docs_watchers_page ON docs_watchers (page_id);

CREATE TABLE IF NOT EXISTS docs_notifications (
    id           VARCHAR(36) PRIMARY KEY,
    tenant_id    BIGINT      NOT NULL,
    user_id      VARCHAR(36) NOT NULL,
    kind         VARCHAR(32) NOT NULL,
    actor_id     VARCHAR(36),
    space_id     VARCHAR(36),
    page_id      VARCHAR(36) REFERENCES docs_pages(id) ON DELETE CASCADE,
    comment_id   VARCHAR(36) REFERENCES docs_comments(id) ON DELETE CASCADE,
    payload      JSONB       NOT NULL DEFAULT '{}'::JSONB,
    read_at      TIMESTAMPTZ,
    emailed_at   TIMESTAMPTZ,
    archived_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_docs_notifications_user
    ON docs_notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_docs_notifications_unread
    ON docs_notifications (user_id) WHERE read_at IS NULL AND archived_at IS NULL;

-- ---------------------------------------------------------------------------
-- Links between pages (backlinks) and block transclusion cache
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_links (
    tenant_id       BIGINT      NOT NULL,
    source_page_id  VARCHAR(36) NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,
    target_page_id  VARCHAR(36) NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,
    -- link | transclusion
    kind            VARCHAR(16) NOT NULL DEFAULT 'link',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (source_page_id, target_page_id, kind)
);
CREATE INDEX IF NOT EXISTS idx_docs_links_target ON docs_links (target_page_id);

CREATE TABLE IF NOT EXISTS docs_transclusion_blocks (
    id            VARCHAR(36) PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL,
    page_id       VARCHAR(36) NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,
    block_id      VARCHAR(40) NOT NULL,
    content       JSONB       NOT NULL,
    text_content  TEXT        NOT NULL DEFAULT '',
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (page_id, block_id)
);

-- ---------------------------------------------------------------------------
-- Templates, labels, import jobs, Lite edit leases
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS docs_templates (
    id              VARCHAR(36)  PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    -- NULL = tenant-wide template
    space_id        VARCHAR(36)  REFERENCES docs_spaces(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    description     TEXT         NOT NULL DEFAULT '',
    icon            VARCHAR(64),
    content         JSONB        NOT NULL,
    text_content    TEXT         NOT NULL DEFAULT '',
    category        VARCHAR(64)  NOT NULL DEFAULT '',
    creator_id      VARCHAR(36),
    last_editor_id  VARCHAR(36),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_docs_templates_tenant
    ON docs_templates (tenant_id, space_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS docs_labels (
    id          VARCHAR(36) PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL,
    space_id    VARCHAR(36) NOT NULL REFERENCES docs_spaces(id) ON DELETE CASCADE,
    name        VARCHAR(64) NOT NULL,
    color       VARCHAR(16) NOT NULL DEFAULT 'gray',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (space_id, name)
);

CREATE TABLE IF NOT EXISTS docs_page_labels (
    page_id     VARCHAR(36) NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,
    label_id    VARCHAR(36) NOT NULL REFERENCES docs_labels(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (page_id, label_id)
);
CREATE INDEX IF NOT EXISTS idx_docs_page_labels_label ON docs_page_labels (label_id);

CREATE TABLE IF NOT EXISTS docs_import_jobs (
    id                VARCHAR(36)   PRIMARY KEY,
    tenant_id         BIGINT        NOT NULL,
    space_id          VARCHAR(36)   NOT NULL REFERENCES docs_spaces(id) ON DELETE CASCADE,
    -- markdown_zip | html_zip | confluence | notion | docx | pdf
    kind              VARCHAR(32)   NOT NULL,
    -- pending | running | succeeded | partial | failed
    status            VARCHAR(16)   NOT NULL DEFAULT 'pending',
    source_path       VARCHAR(1024) NOT NULL,
    file_name         VARCHAR(512)  NOT NULL DEFAULT '',
    target_parent_id  VARCHAR(36),
    stats             JSONB         NOT NULL DEFAULT '{}'::JSONB,
    error             TEXT          NOT NULL DEFAULT '',
    created_by        VARCHAR(36),
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    finished_at       TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_docs_import_jobs_space ON docs_import_jobs (space_id, created_at DESC);

-- Asynchronous space exports. Separate from docs_import_jobs rather than a
-- shared table with a direction column: an import has a source path and a
-- target parent, an export has a result path and a format, and a table whose
-- columns are meaningful for half its rows is one every query has to
-- apologise for.
CREATE TABLE IF NOT EXISTS docs_export_jobs (
    id            VARCHAR(36)   PRIMARY KEY,
    tenant_id     BIGINT        NOT NULL,
    space_id      VARCHAR(36)   NOT NULL REFERENCES docs_spaces(id) ON DELETE CASCADE,
    -- markdown | html
    format        VARCHAR(16)   NOT NULL DEFAULT 'markdown',
    -- pending | running | succeeded | partial | failed
    status        VARCHAR(16)   NOT NULL DEFAULT 'pending',
    -- Where the finished archive was written, in the space's storage backend.
    result_path   VARCHAR(1024) NOT NULL DEFAULT '',
    file_name     VARCHAR(512)  NOT NULL DEFAULT '',
    -- Page counts and skipped-page reasons, for the progress display.
    stats         JSONB         NOT NULL DEFAULT '{}'::JSONB,
    error         TEXT          NOT NULL DEFAULT '',
    -- The export contains exactly what this person could read, so only they
    -- may download it. See internal/docs/service/exportjob.go.
    created_by    VARCHAR(36),
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    finished_at   TIMESTAMPTZ,
    -- Archives are deleted after this, by the maintenance sweep.
    expires_at    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_docs_export_jobs_space ON docs_export_jobs (space_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_docs_export_jobs_expiry ON docs_export_jobs (expires_at)
    WHERE expires_at IS NOT NULL;


-- Exclusive-edit leases used when no collaboration service is configured
-- (Lite edition). Standard deployments never write this table.
CREATE TABLE IF NOT EXISTS docs_edit_leases (
    page_id     VARCHAR(36) PRIMARY KEY REFERENCES docs_pages(id) ON DELETE CASCADE,
    tenant_id   BIGINT      NOT NULL,
    user_id     VARCHAR(36) NOT NULL,
    session_id  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$ BEGIN RAISE NOTICE '[Migration 000120] Done.'; END $$;
