"""Render the generated sections of THIRD_PARTY_NOTICES.md from the scanners' JSON.

    render_notices.py [--check] [--notices FILE] SECTION=scan.json [SECTION=scan.json ...]

THIRD_PARTY_NOTICES.md used to be a hand-maintained snapshot, and it drifted:
modules long gone from every go.mod stayed listed, versions went stale, new
dependencies never appeared. So the parts that are facts about the dependency
tree -- each ecosystem's license summary and full list -- are now rendered
from the scan, between explicit markers:

    <!-- BEGIN GENERATED: go -->
    ...
    <!-- END GENERATED: go -->

Everything outside the markers (the introduction, the bundled-assets table, the
license elections) stays hand-written, because it records judgement rather than
facts a scanner can see.

Without --check, each named section is rewritten in place. With --check nothing
is written: a section whose rendering differs from the file is reported with a
diff and the exit status is 1, which is how tools/license_check.sh fails CI when
a dependency change lands without the notices.

Sections are rendered one at a time, so a scan that can only run in some
environment (the Python ones need uv, the npm ones an installed tree) updates or
verifies its own section and leaves the rest of the file alone. The output is
deterministic -- rows sorted, ties broken by name -- so rendering twice from
the same tree changes nothing.
"""
import argparse
import difflib
import json
import os
import re
import sys
from collections import Counter

# section name -> (scanner kind, noun for the summary column, noun for the list).
SECTIONS = {
    "go": ("go", "Modules", "Module"),
    "npm-frontend": ("npm", "Packages", "Package"),
    "npm-collab": ("npm", "Packages", "Package"),
    "python-docreader": ("python", "Distributions", "Distribution"),
    "python-mcp-server": ("python", "Distributions", "Distribution"),
}

# Facts a scanner cannot establish, keyed by (section, component name).
# Each entry names the result the scanner is expected to produce; if the
# component disappears or the scanner starts classifying it by itself, the
# render fails and asks for the entry to be removed, so this map can never
# outlive the fact it records.
ANNOTATIONS = {
    ("go", "github.com/mattn/go-localereader"): {
        "scanned": "NO-LICENSE-FILE",
        "license": "MIT",
        "note": "no LICENSE file in the module; its README states MIT",
    },
}

HEADER = ("<!-- Generated by tools/licensescan/render_notices.py; do not edit by hand. "
          "Run `tools/license_check.sh notices` to refresh. -->")


class RenderError(Exception):
    pass


def cell(text):
    return text.replace("|", "\\|")


def code_list(paths):
    return ", ".join(f"`{p}`" for p in paths)


def annotate(section, name, scanned, used):
    """Apply the annotation map to one row; returns the license text to show."""
    ann = ANNOTATIONS.get((section, name))
    if ann is None:
        return None
    used.add((section, name))
    if scanned != ann["scanned"]:
        raise RenderError(
            f"the annotation for {name} in render_notices.py expects the scanner to report "
            f"{ann['scanned']}, but it now reports {scanned}; remove or update the annotation")
    return f"{ann['license']} ({ann['note']})"


def go_rows(section, scan, used):
    rows = []
    for r in scan["rows"]:
        spdx = r["spdx"]
        if spdx == "NOT-IN-CACHE":
            raise RenderError(
                f"{r['module']}@{r['version']} is not in the module cache, so the Go scan is incomplete; "
                "run `go mod download` in every module directory (see tools/license_check.sh) and retry")
        text = annotate(section, r["module"], spdx, used)
        repl = r.get("replace") or {}
        if text is None:
            if r.get("this_repository"):
                text = f"{spdx} (this repository; see NOTICE)"
            elif "path" in repl:
                text = f"{spdx} (vendored at {repl['path']}; see {r['license_file']})"
            elif repl:
                target = repl["version"] if repl["module"] == r["module"] else f"{repl['module']} {repl['version']}"
                text = (f"{spdx} ({r['version']} is replaced by {target} in go.mod; "
                        "the license is read from the replacement)")
            else:
                text = spdx
        rows.append((r["module"], r["version"], text))
    # The root go.mod first, then the others alphabetically.
    required_by = sorted({g for r in scan["rows"] for g in r["gomods"]}, key=lambda g: (g != "go.mod", g))
    source = (f"Every module required by {code_list(required_by)}, with their `replace` directives "
              "applied; each license is matched from the module's own license file.")
    return source, rows


def npm_rows(section, scan, used):
    rows = []
    for r in scan["rows"]:
        text = annotate(section, r["name"], r["license"], used)
        if text is None:
            if r["license"] == "NOT-RECORDED":
                text = "UNRESOLVED (platform-specific binary; package-lock.json records no license for it)"
            else:
                text = r["license"]
        rows.append((r["name"], r["version"], text))
    source = (f"Every package `{scan['meta']['lockfile']}` resolves, build tooling included, with the "
              "license each installed package declares (for platform-specific binaries, the license the "
              "lockfile records, so the list is the same on every machine).")
    return source, rows


def python_rows(section, scan, used):
    rows = []
    for r in scan["rows"]:
        text = annotate(section, r["name"], r["license"], used) or r["license"]
        if r["platforms"]:
            text += f" ({', '.join(r['platforms'])} only)"
        rows.append((r["name"], r["version"], text))
    meta = scan["meta"]
    source = (f"The runtime dependencies locked in `{meta['lockfile']}`, as installed for Python "
              f"{meta['python']} (the base image of `{meta['dockerfile']}`) on "
              f"{' and '.join(meta['platforms'])}.")
    return source, rows


RENDERERS = {"go": go_rows, "npm": npm_rows, "python": python_rows}


def render(section, scan, used):
    kind, plural, singular = SECTIONS[section]
    source, rows = RENDERERS[kind](section, scan, used)
    rows.sort(key=lambda r: (r[0].lower(), r[0], r[1]))
    counts = Counter(text for _, _, text in rows)

    out = [HEADER, "", source, "", f"| License | {plural} |", "|---|---|"]
    for text in sorted(counts, key=lambda t: (-counts[t], t)):
        out.append(f"| {cell(text)} | {counts[text]} |")
    out += ["", "<details>", f"<summary>Full list ({len(rows)} {plural.lower()})</summary>", "",
            f"| {singular} | Version | License |", "|---|---|---|"]
    for name, version, text in rows:
        out.append(f"| `{name}` | {version} | {cell(text)} |")
    out += ["", "</details>"]
    return "\n".join(out) + "\n"


def splice(text, section, body):
    pattern = re.compile(
        rf"(<!-- BEGIN GENERATED: {re.escape(section)} -->\n)(.*?)(<!-- END GENERATED: {re.escape(section)} -->)",
        re.S)
    matches = pattern.findall(text)
    if len(matches) != 1:
        raise RenderError(
            f"expected exactly one '<!-- BEGIN GENERATED: {section} -->' ... "
            f"'<!-- END GENERATED: {section} -->' pair in the notices file, found {len(matches)}")
    old = matches[0][1]
    return pattern.sub(lambda m: m.group(1) + body + m.group(3), text), old


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="verify instead of writing; exit 1 on a difference")
    ap.add_argument("--notices", default="THIRD_PARTY_NOTICES.md")
    ap.add_argument("scans", nargs="+", metavar="SECTION=JSON")
    args = ap.parse_args()

    with open(args.notices, "rb") as fh:
        raw = fh.read()
    # Compare and splice with LF; write back whatever line ending the checkout
    # uses, so a Windows checkout with autocrlf neither fails the check nor
    # rewrites every line.
    newline = "\r\n" if b"\r\n" in raw else "\n"
    text = raw.decode("utf-8").replace("\r\n", "\n")

    used = set()
    stale = []
    try:
        for spec in args.scans:
            section, sep, path = spec.partition("=")
            if not sep or section not in SECTIONS:
                raise RenderError(f"'{spec}': expected SECTION=JSON with SECTION one of {', '.join(SECTIONS)}")
            with open(path, encoding="utf-8") as fh:
                scan = json.load(fh)
            body = render(section, scan, used)
            text, old = splice(text, section, body)
            if old != body:
                stale.append(section)
                if args.check:
                    diff = list(difflib.unified_diff(
                        old.splitlines(), body.splitlines(),
                        f"{args.notices} ({section}, committed)", f"{args.notices} ({section}, from the scan)",
                        lineterm="", n=0))
                    for line in diff[:40]:
                        print(line)
                    if len(diff) > 40:
                        print(f"... {len(diff) - 40} more diff lines")
        # An annotation whose component was never seen is stale too -- but only
        # if the section it belongs to was actually rendered in this run.
        rendered = {s.partition("=")[0] for s in args.scans}
        for section, name in sorted(set(ANNOTATIONS) - used):
            if section in rendered:
                raise RenderError(f"the annotation for {name} in render_notices.py matches nothing the "
                                  f"{section} scan found; remove it")
    except RenderError as e:
        print(f"render_notices: {e}", file=sys.stderr)
        return 2

    if args.check:
        if stale:
            print(f"out of date: {', '.join(stale)}")
            return 1
        return 0

    if stale:
        tmp = args.notices + ".tmp"
        with open(tmp, "w", encoding="utf-8", newline=newline) as fh:
            fh.write(text)
        os.replace(tmp, args.notices)
    for spec in args.scans:
        section = spec.partition("=")[0]
        print(f"{section}: {'updated' if section in stale else 'already current'}")
    return 0


sys.exit(main())
