/**
 * Runtime switches for how the community edition talks about the Enterprise
 * edition. Both come from `window.__RUNTIME_CONFIG__` (generated by the Docker
 * entrypoint from environment variables), so an operator can change them by
 * restarting the container, without rebuilding the image.
 *
 * They are read on every call rather than captured at import time: config.js is
 * loaded before the bundle, but tests (and any future hot reload of the config)
 * should see the current value.
 */

/**
 * Where "learn more" links point. Empty when unset or when the value is not an
 * absolute http(s) URL: a link that is not clearly a web page is worse than no
 * link, and this also keeps `javascript:` style values out of an href.
 */
export function getEnterpriseInfoUrl(): string {
  const raw = window.__RUNTIME_CONFIG__?.ENTERPRISE_INFO_URL;
  if (typeof raw !== "string") return "";
  const value = raw.trim();
  if (!value) return "";
  try {
    const url = new URL(value);
    return url.protocol === "https:" || url.protocol === "http:" ? url.toString() : "";
  } catch {
    return "";
  }
}

/**
 * True when the operator asked the public build not to promote the Enterprise
 * edition. Only unavailable-state teasers and the Enterprise settings section
 * honour it; features the backend reports as enabled are never hidden.
 */
export function isEnterprisePromotionHidden(): boolean {
  const raw: unknown = window.__RUNTIME_CONFIG__?.HIDE_ENTERPRISE_PROMOTION;
  return raw === true || raw === "true";
}
