// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: docreader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ParserEngine          string                 `protobuf:"bytes,1,opt,name=parser_engine,json=parserEngine,proto3" json:"parser_engine,omitempty"`
	ParserEngineOverrides map[string]string      `protobuf:"bytes,2,rep,name=parser_engine_overrides,json=parserEngineOverrides,proto3" json:"parser_engine_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReadConfig) Reset() {
	*x = ReadConfig{}
	mi := &file_docreader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadConfig) ProtoMessage() {}

func (x *ReadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadConfig.ProtoReflect.Descriptor instead.
func (*ReadConfig) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{0}
}

func (x *ReadConfig) GetParserEngine() string {
	if x != nil {
		return x.ParserEngine
	}
	return ""
}

func (x *ReadConfig) GetParserEngineOverrides() map[string]string {
	if x != nil {
		return x.ParserEngineOverrides
	}
	return nil
}

// Unified read request: set file_content for file mode, url for URL mode.
// file_path is a shared-volume alternative to file_content for large media
// (e.g. multi-GB videos): the Go app passes a path inside the volume both
// containers mount instead of streaming the bytes through gRPC memory.
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Config        *ReadConfig            `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,8,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_docreader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{1}
}

func (x *ReadRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ReadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReadRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *ReadRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReadRequest) GetConfig() *ReadConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ReadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReadRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type ImageRef struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Filename    string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalRef string                 `protobuf:"bytes,2,opt,name=original_ref,json=originalRef,proto3" json:"original_ref,omitempty"`
	MimeType    string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ImageData   []byte                 `protobuf:"bytes,5,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// Timestamp of this frame within the source media, in milliseconds.
	// Set for video keyframes; 0 for ordinary document images.
	TimestampMs   int64 `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRef) Reset() {
	*x = ImageRef{}
	mi := &file_docreader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRef) ProtoMessage() {}

func (x *ImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRef.ProtoReflect.Descriptor instead.
func (*ImageRef) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{2}
}

func (x *ImageRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageRef) GetOriginalRef() string {
	if x != nil {
		return x.OriginalRef
	}
	return ""
}

func (x *ImageRef) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageRef) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ImageRef) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// MediaInfo describes the audio/video characteristics of a parsed media
// file. Present only when the parsed file is a video.
type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsVideo       bool                   `protobuf:"varint,1,opt,name=is_video,json=isVideo,proto3" json:"is_video,omitempty"`
	DurationMs    int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	HasAudio      bool                   `protobuf:"varint,3,opt,name=has_audio,json=hasAudio,proto3" json:"has_audio,omitempty"`
	AudioMimeType string                 `protobuf:"bytes,4,opt,name=audio_mime_type,json=audioMimeType,proto3" json:"audio_mime_type,omitempty"` // MIME of the extracted audio track (e.g. audio/mpeg)
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_docreader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{3}
}

func (x *MediaInfo) GetIsVideo() bool {
	if x != nil {
		return x.IsVideo
	}
	return false
}

func (x *MediaInfo) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MediaInfo) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

func (x *MediaInfo) GetAudioMimeType() string {
	if x != nil {
		return x.AudioMimeType
	}
	return ""
}

func (x *MediaInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Metadata header for a streamed read. Sent exactly once, before any image.
type ReadStreamMeta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarkdownContent string                 `protobuf:"bytes,1,opt,name=markdown_content,json=markdownContent,proto3" json:"markdown_content,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ImageCount      uint32                 `protobuf:"varint,5,opt,name=image_count,json=imageCount,proto3" json:"image_count,omitempty"` // best-effort total image count (0 if unknown)
	Media           *MediaInfo             `protobuf:"bytes,6,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadStreamMeta) Reset() {
	*x = ReadStreamMeta{}
	mi := &file_docreader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamMeta) ProtoMessage() {}

func (x *ReadStreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamMeta.ProtoReflect.Descriptor instead.
func (*ReadStreamMeta) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{4}
}

func (x *ReadStreamMeta) GetMarkdownContent() string {
	if x != nil {
		return x.MarkdownContent
	}
	return ""
}

func (x *ReadStreamMeta) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReadStreamMeta) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadStreamMeta) GetImageCount() uint32 {
	if x != nil {
		return x.ImageCount
	}
	return 0
}

func (x *ReadStreamMeta) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// AudioChunk carries one transport slice of the extracted audio track.
// Slices arrive in order after the meta frame and before image frames.
// The track is split into fixed-duration SEGMENTS (so ASR providers with
// small payload caps and no timestamp support still yield a usable
// timeline); slices belonging to the same segment share segment_index /
// start_ms / end_ms and are concatenated by the client in arrival order.
type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SegmentIndex  uint32                 `protobuf:"varint,2,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"`
	StartMs       int64                  `protobuf:"varint,3,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs         int64                  `protobuf:"varint,4,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_docreader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{5}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetSegmentIndex() uint32 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *AudioChunk) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *AudioChunk) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

// One frame of a ReadStream. The first frame carries `meta`; subsequent
// frames carry audio slices (for videos with an audio track) and then one
// frame per image.
type ReadStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ReadStreamResponse_Meta
	//	*ReadStreamResponse_Image
	//	*ReadStreamResponse_Audio
	Payload       isReadStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamResponse) Reset() {
	*x = ReadStreamResponse{}
	mi := &file_docreader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamResponse) ProtoMessage() {}

func (x *ReadStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamResponse.ProtoReflect.Descriptor instead.
func (*ReadStreamResponse) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{6}
}

func (x *ReadStreamResponse) GetPayload() isReadStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReadStreamResponse) GetMeta() *ReadStreamMeta {
	if x != nil {
		if x, ok := x.Payload.(*ReadStreamResponse_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *ReadStreamResponse) GetImage() *ImageRef {
	if x != nil {
		if x, ok := x.Payload.(*ReadStreamResponse_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ReadStreamResponse) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Payload.(*ReadStreamResponse_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

type isReadStreamResponse_Payload interface {
	isReadStreamResponse_Payload()
}

type ReadStreamResponse_Meta struct {
	Meta *ReadStreamMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type ReadStreamResponse_Image struct {
	Image *ImageRef `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type ReadStreamResponse_Audio struct {
	Audio *AudioChunk `protobuf:"bytes,3,opt,name=audio,proto3,oneof"`
}

func (*ReadStreamResponse_Meta) isReadStreamResponse_Payload() {}

func (*ReadStreamResponse_Image) isReadStreamResponse_Payload() {}

func (*ReadStreamResponse_Audio) isReadStreamResponse_Payload() {}

type ListEnginesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigOverrides map[string]string      `protobuf:"bytes,1,rep,name=config_overrides,json=configOverrides,proto3" json:"config_overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListEnginesRequest) Reset() {
	*x = ListEnginesRequest{}
	mi := &file_docreader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnginesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnginesRequest) ProtoMessage() {}

func (x *ListEnginesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnginesRequest.ProtoReflect.Descriptor instead.
func (*ListEnginesRequest) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{7}
}

func (x *ListEnginesRequest) GetConfigOverrides() map[string]string {
	if x != nil {
		return x.ConfigOverrides
	}
	return nil
}

type ParserEngineInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FileTypes         []string               `protobuf:"bytes,3,rep,name=file_types,json=fileTypes,proto3" json:"file_types,omitempty"`
	Available         bool                   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	UnavailableReason string                 `protobuf:"bytes,5,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ParserEngineInfo) Reset() {
	*x = ParserEngineInfo{}
	mi := &file_docreader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParserEngineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserEngineInfo) ProtoMessage() {}

func (x *ParserEngineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserEngineInfo.ProtoReflect.Descriptor instead.
func (*ParserEngineInfo) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{8}
}

func (x *ParserEngineInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParserEngineInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParserEngineInfo) GetFileTypes() []string {
	if x != nil {
		return x.FileTypes
	}
	return nil
}

func (x *ParserEngineInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ParserEngineInfo) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

type ListEnginesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Engines       []*ParserEngineInfo    `protobuf:"bytes,1,rep,name=engines,proto3" json:"engines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnginesResponse) Reset() {
	*x = ListEnginesResponse{}
	mi := &file_docreader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnginesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnginesResponse) ProtoMessage() {}

func (x *ListEnginesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docreader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnginesResponse.ProtoReflect.Descriptor instead.
func (*ListEnginesResponse) Descriptor() ([]byte, []int) {
	return file_docreader_proto_rawDescGZIP(), []int{9}
}

func (x *ListEnginesResponse) GetEngines() []*ParserEngineInfo {
	if x != nil {
		return x.Engines
	}
	return nil
}

var File_docreader_proto protoreflect.FileDescriptor

const file_docreader_proto_rawDesc = "" +
	"\n" +
	"\x0fdocreader.proto\x12\tdocreader\"\xe5\x01\n" +
	"\n" +
	"ReadConfig\x12#\n" +
	"\rparser_engine\x18\x01 \x01(\tR\fparserEngine\x12h\n" +
	"\x17parser_engine_overrides\x18\x02 \x03(\v20.docreader.ReadConfig.ParserEngineOverridesEntryR\x15parserEngineOverrides\x1aH\n" +
	"\x1aParserEngineOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x01\n" +
	"\vReadRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12-\n" +
	"\x06config\x18\x06 \x01(\v2\x15.docreader.ReadConfigR\x06config\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12\x1b\n" +
	"\tfile_path\x18\b \x01(\tR\bfilePath\"\xbb\x01\n" +
	"\bImageRef\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\foriginal_ref\x18\x02 \x01(\tR\voriginalRef\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"image_data\x18\x05 \x01(\fR\timageData\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMsJ\x04\b\x04\x10\x05R\vstorage_key\"\xba\x01\n" +
	"\tMediaInfo\x12\x19\n" +
	"\bis_video\x18\x01 \x01(\bR\aisVideo\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\thas_audio\x18\x03 \x01(\bR\bhasAudio\x12&\n" +
	"\x0faudio_mime_type\x18\x04 \x01(\tR\raudioMimeType\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\"\xb6\x02\n" +
	"\x0eReadStreamMeta\x12)\n" +
	"\x10markdown_content\x18\x01 \x01(\tR\x0fmarkdownContent\x12C\n" +
	"\bmetadata\x18\x03 \x03(\v2'.docreader.ReadStreamMeta.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1f\n" +
	"\vimage_count\x18\x05 \x01(\rR\n" +
	"imageCount\x12*\n" +
	"\x05media\x18\x06 \x01(\v2\x14.docreader.MediaInfoR\x05media\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03R\x0eimage_dir_path\"w\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12#\n" +
	"\rsegment_index\x18\x02 \x01(\rR\fsegmentIndex\x12\x19\n" +
	"\bstart_ms\x18\x03 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x04 \x01(\x03R\x05endMs\"\xac\x01\n" +
	"\x12ReadStreamResponse\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x19.docreader.ReadStreamMetaH\x00R\x04meta\x12+\n" +
	"\x05image\x18\x02 \x01(\v2\x13.docreader.ImageRefH\x00R\x05image\x12-\n" +
	"\x05audio\x18\x03 \x01(\v2\x15.docreader.AudioChunkH\x00R\x05audioB\t\n" +
	"\apayload\"\xb7\x01\n" +
	"\x12ListEnginesRequest\x12]\n" +
	"\x10config_overrides\x18\x01 \x03(\v22.docreader.ListEnginesRequest.ConfigOverridesEntryR\x0fconfigOverrides\x1aB\n" +
	"\x14ConfigOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x10ParserEngineInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"file_types\x18\x03 \x03(\tR\tfileTypes\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\bR\tavailable\x12-\n" +
	"\x12unavailable_reason\x18\x05 \x01(\tR\x11unavailableReason\"L\n" +
	"\x13ListEnginesResponse\x125\n" +
	"\aengines\x18\x01 \x03(\v2\x1b.docreader.ParserEngineInfoR\aengines2\xa4\x01\n" +
	"\tDocReader\x12G\n" +
	"\n" +
	"ReadStream\x12\x16.docreader.ReadRequest\x1a\x1d.docreader.ReadStreamResponse\"\x000\x01\x12N\n" +
	"\vListEngines\x12\x1d.docreader.ListEnginesRequest\x1a\x1e.docreader.ListEnginesResponse\"\x00B0Z.github.com/magicyuan876/yuheng/docreader/protob\x06proto3"

var (
	file_docreader_proto_rawDescOnce sync.Once
	file_docreader_proto_rawDescData []byte
)

func file_docreader_proto_rawDescGZIP() []byte {
	file_docreader_proto_rawDescOnce.Do(func() {
		file_docreader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docreader_proto_rawDesc), len(file_docreader_proto_rawDesc)))
	})
	return file_docreader_proto_rawDescData
}

var file_docreader_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_docreader_proto_goTypes = []any{
	(*ReadConfig)(nil),          // 0: docreader.ReadConfig
	(*ReadRequest)(nil),         // 1: docreader.ReadRequest
	(*ImageRef)(nil),            // 2: docreader.ImageRef
	(*MediaInfo)(nil),           // 3: docreader.MediaInfo
	(*ReadStreamMeta)(nil),      // 4: docreader.ReadStreamMeta
	(*AudioChunk)(nil),          // 5: docreader.AudioChunk
	(*ReadStreamResponse)(nil),  // 6: docreader.ReadStreamResponse
	(*ListEnginesRequest)(nil),  // 7: docreader.ListEnginesRequest
	(*ParserEngineInfo)(nil),    // 8: docreader.ParserEngineInfo
	(*ListEnginesResponse)(nil), // 9: docreader.ListEnginesResponse
	nil,                         // 10: docreader.ReadConfig.ParserEngineOverridesEntry
	nil,                         // 11: docreader.ReadStreamMeta.MetadataEntry
	nil,                         // 12: docreader.ListEnginesRequest.ConfigOverridesEntry
}
var file_docreader_proto_depIdxs = []int32{
	10, // 0: docreader.ReadConfig.parser_engine_overrides:type_name -> docreader.ReadConfig.ParserEngineOverridesEntry
	0,  // 1: docreader.ReadRequest.config:type_name -> docreader.ReadConfig
	11, // 2: docreader.ReadStreamMeta.metadata:type_name -> docreader.ReadStreamMeta.MetadataEntry
	3,  // 3: docreader.ReadStreamMeta.media:type_name -> docreader.MediaInfo
	4,  // 4: docreader.ReadStreamResponse.meta:type_name -> docreader.ReadStreamMeta
	2,  // 5: docreader.ReadStreamResponse.image:type_name -> docreader.ImageRef
	5,  // 6: docreader.ReadStreamResponse.audio:type_name -> docreader.AudioChunk
	12, // 7: docreader.ListEnginesRequest.config_overrides:type_name -> docreader.ListEnginesRequest.ConfigOverridesEntry
	8,  // 8: docreader.ListEnginesResponse.engines:type_name -> docreader.ParserEngineInfo
	1,  // 9: docreader.DocReader.ReadStream:input_type -> docreader.ReadRequest
	7,  // 10: docreader.DocReader.ListEngines:input_type -> docreader.ListEnginesRequest
	6,  // 11: docreader.DocReader.ReadStream:output_type -> docreader.ReadStreamResponse
	9,  // 12: docreader.DocReader.ListEngines:output_type -> docreader.ListEnginesResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_docreader_proto_init() }
func file_docreader_proto_init() {
	if File_docreader_proto != nil {
		return
	}
	file_docreader_proto_msgTypes[6].OneofWrappers = []any{
		(*ReadStreamResponse_Meta)(nil),
		(*ReadStreamResponse_Image)(nil),
		(*ReadStreamResponse_Audio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docreader_proto_rawDesc), len(file_docreader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docreader_proto_goTypes,
		DependencyIndexes: file_docreader_proto_depIdxs,
		MessageInfos:      file_docreader_proto_msgTypes,
	}.Build()
	File_docreader_proto = out.File
	file_docreader_proto_goTypes = nil
	file_docreader_proto_depIdxs = nil
}
