// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: docreader.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocReader_ReadStream_FullMethodName  = "/docreader.DocReader/ReadStream"
	DocReader_ListEngines_FullMethodName = "/docreader.DocReader/ListEngines"
)

// DocReaderClient is the client API for DocReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Removing a field from a message that is still in use leaves its number and
// name `reserved`. Reusing either for a new field would let a peer built from
// the previous schema, such as a half-upgraded stack running a new app against
// an old docreader image, decode the old field as the new one without any
// error. A message removed outright needs no reservation: nothing can reuse
// its fields.
type DocReaderClient interface {
	// ReadStream parses one document. It first emits one ReadStreamResponse
	// carrying the parse metadata (markdown / metadata / error), then the audio
	// track of a video, then one message per image. Streaming is the only read
	// path because it keeps every gRPC message small: a large scanned PDF
	// (hundreds of page images) would exceed any single-message cap, and
	// neither end has to hold the whole result in memory at once.
	ReadStream(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadStreamResponse], error)
	ListEngines(ctx context.Context, in *ListEnginesRequest, opts ...grpc.CallOption) (*ListEnginesResponse, error)
}

type docReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewDocReaderClient(cc grpc.ClientConnInterface) DocReaderClient {
	return &docReaderClient{cc}
}

func (c *docReaderClient) ReadStream(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DocReader_ServiceDesc.Streams[0], DocReader_ReadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRequest, ReadStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocReader_ReadStreamClient = grpc.ServerStreamingClient[ReadStreamResponse]

func (c *docReaderClient) ListEngines(ctx context.Context, in *ListEnginesRequest, opts ...grpc.CallOption) (*ListEnginesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnginesResponse)
	err := c.cc.Invoke(ctx, DocReader_ListEngines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocReaderServer is the server API for DocReader service.
// All implementations must embed UnimplementedDocReaderServer
// for forward compatibility.
//
// Removing a field from a message that is still in use leaves its number and
// name `reserved`. Reusing either for a new field would let a peer built from
// the previous schema, such as a half-upgraded stack running a new app against
// an old docreader image, decode the old field as the new one without any
// error. A message removed outright needs no reservation: nothing can reuse
// its fields.
type DocReaderServer interface {
	// ReadStream parses one document. It first emits one ReadStreamResponse
	// carrying the parse metadata (markdown / metadata / error), then the audio
	// track of a video, then one message per image. Streaming is the only read
	// path because it keeps every gRPC message small: a large scanned PDF
	// (hundreds of page images) would exceed any single-message cap, and
	// neither end has to hold the whole result in memory at once.
	ReadStream(*ReadRequest, grpc.ServerStreamingServer[ReadStreamResponse]) error
	ListEngines(context.Context, *ListEnginesRequest) (*ListEnginesResponse, error)
	mustEmbedUnimplementedDocReaderServer()
}

// UnimplementedDocReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocReaderServer struct{}

func (UnimplementedDocReaderServer) ReadStream(*ReadRequest, grpc.ServerStreamingServer[ReadStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadStream not implemented")
}
func (UnimplementedDocReaderServer) ListEngines(context.Context, *ListEnginesRequest) (*ListEnginesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEngines not implemented")
}
func (UnimplementedDocReaderServer) mustEmbedUnimplementedDocReaderServer() {}
func (UnimplementedDocReaderServer) testEmbeddedByValue()                   {}

// UnsafeDocReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocReaderServer will
// result in compilation errors.
type UnsafeDocReaderServer interface {
	mustEmbedUnimplementedDocReaderServer()
}

func RegisterDocReaderServer(s grpc.ServiceRegistrar, srv DocReaderServer) {
	// If the following call panics, it indicates UnimplementedDocReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocReader_ServiceDesc, srv)
}

func _DocReader_ReadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocReaderServer).ReadStream(m, &grpc.GenericServerStream[ReadRequest, ReadStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DocReader_ReadStreamServer = grpc.ServerStreamingServer[ReadStreamResponse]

func _DocReader_ListEngines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnginesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocReaderServer).ListEngines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocReader_ListEngines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocReaderServer).ListEngines(ctx, req.(*ListEnginesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocReader_ServiceDesc is the grpc.ServiceDesc for DocReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docreader.DocReader",
	HandlerType: (*DocReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEngines",
			Handler:    _DocReader_ListEngines_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadStream",
			Handler:       _DocReader_ReadStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docreader.proto",
}
