import type { Component } from "vue";

import {
  ArrowDownIcon,
  ArrowDownWideNarrowIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BoldIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CodeIcon,
  CopyIcon,
  HighlighterIcon,
  InfoIcon,
  ItalicIcon,
  LinkIcon,
  ListIcon,
  MessageSquareIcon,
  MoveHorizontalIcon,
  PaintBucketIcon,
  RemoveFormattingIcon,
  SquareCheckIcon,
  SquareMinusIcon,
  StrikethroughIcon,
  Table2Icon,
  TableCellsMergeIcon,
  TableCellsSplitIcon,
  TableIcon,
  TextQuoteIcon,
  Trash2Icon,
  TypeIcon,
  UnderlineIcon,
  CircleMinusIcon,
  Columns2Icon,
  ListOrderedIcon,
  ChartScatterIcon,
  MinusIcon,
  NetworkIcon,
  PaletteIcon,
  SeparatorHorizontalIcon,
  SigmaIcon,
  TagIcon,
} from "@lucide/vue";

/**
 * The editor's command catalogues speak in tdesign icon names (they are data,
 * and a test guards that every name exists). This is where those names meet
 * the lucide set the UI now renders; lucideIconMap.test.ts guards that every
 * catalogue name has an entry here, since a missing one silently falls back.
 */
export const EDITOR_ICONS: Record<string, Component> = {
  "arrow-down": ArrowDownIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  "chart-bubble": ChartScatterIcon,
  "chat-bubble": MessageSquareIcon,
  "check-rectangle": SquareCheckIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "clear-formatting": RemoveFormattingIcon,
  code: CodeIcon,
  copy: CopyIcon,
  delete: Trash2Icon,
  "expand-horizontal": MoveHorizontalIcon,
  "fill-color": PaintBucketIcon,
  formula: SigmaIcon,
  highlight: HighlighterIcon,
  "info-circle": InfoIcon,
  link: LinkIcon,
  "list-numbered": ListOrderedIcon,
  "merge-cells": TableCellsMergeIcon,
  minus: MinusIcon,
  "minus-circle": CircleMinusIcon,
  "minus-rectangle": SquareMinusIcon,
  "order-descending": ArrowDownWideNarrowIcon,
  "order-list": ListIcon,
  "page-first": SeparatorHorizontalIcon,
  palette: PaletteIcon,
  quote: TextQuoteIcon,
  sitemap: NetworkIcon,
  table: TableIcon,
  "table-1": TableIcon,
  "table-2": Table2Icon,
  "table-split": TableCellsSplitIcon,
  tag: TagIcon,
  text: TypeIcon,
  "textformat-bold": BoldIcon,
  "textformat-italic": ItalicIcon,
  "textformat-strikethrough": StrikethroughIcon,
  "textformat-underline": UnderlineIcon,
  "view-column": Columns2Icon,
};

/** The icon for a catalogue name, or the fallback when the name is unknown. */
export function editorIcon(name: string | undefined, fallback: Component): Component {
  return (name && EDITOR_ICONS[name]) || fallback;
}
